services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    env_file:
      - frontend/.env  # Load environment variables from the frontend .env file

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Path to your backend Dockerfile
    ports:
      - "5000:5000"  # Expose backend on port 5000
    env_file:
      - backend/.env  # Load environment variables from the backend .env file
    environment:
      - NODE_ENV=development  # Set environment variables if needed
    depends_on:
      - database  # Ensure the backend starts after the database (optional)

  # Optional: If you have a database service, you can add it here
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ezFinance
      POSTGRES_DB: ezfinance
    ports:
      - "5432:5432"  # Expose database port
